### ISSUE TITLE
info: Initiating a Pause

### ISSUE THREAD

**Issue by fearocanity** [fearocanity/ebtrfio-bot#26]
Week of pause, allot a portion of time for rest.
This issue will close when the period is over.

**Comment by fearocanity** [comment]
Okay i think i'm able to manage it now.

**Comment by Rendevior** [comment]
> Again, but this one might last longer due to workloads We have robotics project on school, so i will be out of duty for months. :<

Should i manage it immediately until you came back?

**Comment by Rendevior** [comment]
Just create me something so i can start.

**Comment by fearocanity** [comment]
> Just create me something so i can start.

I'm on it. I was able to finish our project myself.
